// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ComicsColumns holds the columns for the "comics" table.
	ComicsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "author", Type: field.TypeString},
		{Name: "like", Type: field.TypeString},
	}
	// ComicsTable holds the schema information for the "comics" table.
	ComicsTable = &schema.Table{
		Name:        "comics",
		Columns:     ComicsColumns,
		PrimaryKey:  []*schema.Column{ComicsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GenresColumns holds the columns for the "genres" table.
	GenresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// GenresTable holds the schema information for the "genres" table.
	GenresTable = &schema.Table{
		Name:        "genres",
		Columns:     GenresColumns,
		PrimaryKey:  []*schema.Column{GenresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ComicGenresColumns holds the columns for the "comic_genres" table.
	ComicGenresColumns = []*schema.Column{
		{Name: "comic_id", Type: field.TypeInt},
		{Name: "genre_id", Type: field.TypeInt},
	}
	// ComicGenresTable holds the schema information for the "comic_genres" table.
	ComicGenresTable = &schema.Table{
		Name:       "comic_genres",
		Columns:    ComicGenresColumns,
		PrimaryKey: []*schema.Column{ComicGenresColumns[0], ComicGenresColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comic_genres_comic_id",
				Columns:    []*schema.Column{ComicGenresColumns[0]},
				RefColumns: []*schema.Column{ComicsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "comic_genres_genre_id",
				Columns:    []*schema.Column{ComicGenresColumns[1]},
				RefColumns: []*schema.Column{GenresColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ComicsTable,
		GenresTable,
		ComicGenresTable,
	}
)

func init() {
	ComicGenresTable.ForeignKeys[0].RefTable = ComicsTable
	ComicGenresTable.ForeignKeys[1].RefTable = GenresTable
}
