// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/RiskyFeryansyahP/ir-comics-recommendation/ent/comic"
	"github.com/RiskyFeryansyahP/ir-comics-recommendation/ent/genre"
)

// GenreCreate is the builder for creating a Genre entity.
type GenreCreate struct {
	config
	mutation *GenreMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (gc *GenreCreate) SetName(s string) *GenreCreate {
	gc.mutation.SetName(s)
	return gc
}

// AddComicIDs adds the "comics" edge to the Comic entity by IDs.
func (gc *GenreCreate) AddComicIDs(ids ...int) *GenreCreate {
	gc.mutation.AddComicIDs(ids...)
	return gc
}

// AddComics adds the "comics" edges to the Comic entity.
func (gc *GenreCreate) AddComics(c ...*Comic) *GenreCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return gc.AddComicIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (gc *GenreCreate) Mutation() *GenreMutation {
	return gc.mutation
}

// Save creates the Genre in the database.
func (gc *GenreCreate) Save(ctx context.Context) (*Genre, error) {
	var (
		err  error
		node *Genre
	)
	if len(gc.hooks) == 0 {
		if err = gc.check(); err != nil {
			return nil, err
		}
		node, err = gc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GenreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gc.check(); err != nil {
				return nil, err
			}
			gc.mutation = mutation
			node, err = gc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(gc.hooks) - 1; i >= 0; i-- {
			mut = gc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GenreCreate) SaveX(ctx context.Context) *Genre {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (gc *GenreCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	return nil
}

func (gc *GenreCreate) sqlSave(ctx context.Context) (*Genre, error) {
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (gc *GenreCreate) createSpec() (*Genre, *sqlgraph.CreateSpec) {
	var (
		_node = &Genre{config: gc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: genre.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: genre.FieldID,
			},
		}
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: genre.FieldName,
		})
		_node.Name = value
	}
	if nodes := gc.mutation.ComicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.ComicsTable,
			Columns: genre.ComicsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: comic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GenreCreateBulk is the builder for creating many Genre entities in bulk.
type GenreCreateBulk struct {
	config
	builders []*GenreCreate
}

// Save creates the Genre entities in the database.
func (gcb *GenreCreateBulk) Save(ctx context.Context) ([]*Genre, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Genre, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GenreCreateBulk) SaveX(ctx context.Context) []*Genre {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
