// Code generated by entc, DO NOT EDIT.

package genre

const (
	// Label holds the string label denoting the genre type in the database.
	Label = "genre"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeComics holds the string denoting the comics edge name in mutations.
	EdgeComics = "comics"
	// Table holds the table name of the genre in the database.
	Table = "genres"
	// ComicsTable is the table the holds the comics relation/edge. The primary key declared below.
	ComicsTable = "comic_genres"
	// ComicsInverseTable is the table name for the Comic entity.
	// It exists in this package in order to avoid circular dependency with the "comic" package.
	ComicsInverseTable = "comics"
)

// Columns holds all SQL columns for genre fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// ComicsPrimaryKey and ComicsColumn2 are the table columns denoting the
	// primary key for the comics relation (M2M).
	ComicsPrimaryKey = []string{"comic_id", "genre_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
