// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comic is the predicate function for comic builders.
type Comic func(*sql.Selector)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)
